//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", ConfigurationName = "z_sales_interface")]
public interface z_sales_interface
{

    // CODEGEN: Generating message contract since the operation Z_SALES_INTERFACE is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrder", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    Z_SALES_INTERFACEResponse1 Z_SALES_INTERFACE(Z_SALES_INTERFACERequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrder", ReplyAction = "*")]
    System.Threading.Tasks.Task<Z_SALES_INTERFACEResponse1> Z_SALES_INTERFACEAsync(Z_SALES_INTERFACERequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class Z_SALES_INTERFACE
{

    private ZSALES_ORDER iM_ORDERField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public ZSALES_ORDER IM_ORDER
    {
        get
        {
            return this.iM_ORDERField;
        }
        set
        {
            this.iM_ORDERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_ORDER
{

    private string gUIDField;

    private string sERVICETYPEField;

    private string rEPTYPEField;

    private string dOCTYPEField;

    private string aCCField;

    private string uNIQORDIDField;

    private string sENDEMAILField;

    private string sTARTDATEField;

    private string eNDDATEField;

    private ZSALES_LICENCEE[] lICField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string SERVICETYPE
    {
        get
        {
            return this.sERVICETYPEField;
        }
        set
        {
            this.sERVICETYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string REPTYPE
    {
        get
        {
            return this.rEPTYPEField;
        }
        set
        {
            this.rEPTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string DOCTYPE
    {
        get
        {
            return this.dOCTYPEField;
        }
        set
        {
            this.dOCTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string ACC
    {
        get
        {
            return this.aCCField;
        }
        set
        {
            this.aCCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string UNIQORDID
    {
        get
        {
            return this.uNIQORDIDField;
        }
        set
        {
            this.uNIQORDIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string SENDEMAIL
    {
        get
        {
            return this.sENDEMAILField;
        }
        set
        {
            this.sENDEMAILField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string STARTDATE
    {
        get
        {
            return this.sTARTDATEField;
        }
        set
        {
            this.sTARTDATEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string ENDDATE
    {
        get
        {
            return this.eNDDATEField;
        }
        set
        {
            this.eNDDATEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZSALES_LICENCEE[] LIC
    {
        get
        {
            return this.lICField;
        }
        set
        {
            this.lICField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_LICENCEE
{

    private string lNUMField;

    private string lNAME1Field;

    private string lNAME2Field;

    private string lNUM2Field;

    private string lNUM2NAMEField;

    private string cITYField;

    private string aDMINField;

    private string cTRYField;

    private string pCODEField;

    private ZSALES_DELPT[] dELPTField;

    private ZSALES_VESSELS[] vESSELSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string LNUM
    {
        get
        {
            return this.lNUMField;
        }
        set
        {
            this.lNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string LNAME1
    {
        get
        {
            return this.lNAME1Field;
        }
        set
        {
            this.lNAME1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string LNAME2
    {
        get
        {
            return this.lNAME2Field;
        }
        set
        {
            this.lNAME2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string LNUM2
    {
        get
        {
            return this.lNUM2Field;
        }
        set
        {
            this.lNUM2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string LNUM2NAME
    {
        get
        {
            return this.lNUM2NAMEField;
        }
        set
        {
            this.lNUM2NAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string CITY
    {
        get
        {
            return this.cITYField;
        }
        set
        {
            this.cITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string ADMIN
    {
        get
        {
            return this.aDMINField;
        }
        set
        {
            this.aDMINField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string CTRY
    {
        get
        {
            return this.cTRYField;
        }
        set
        {
            this.cTRYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string PCODE
    {
        get
        {
            return this.pCODEField;
        }
        set
        {
            this.pCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZSALES_DELPT[] DELPT
    {
        get
        {
            return this.dELPTField;
        }
        set
        {
            this.dELPTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZSALES_VESSELS[] VESSELS
    {
        get
        {
            return this.vESSELSField;
        }
        set
        {
            this.vESSELSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_DELPT
{

    private string dELIVERYPTField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string DELIVERYPT
    {
        get
        {
            return this.dELIVERYPTField;
        }
        set
        {
            this.dELIVERYPTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_PRODUCT
{

    private string idField;

    private string sUBSCRTYPField;

    private string dURField;

    private string dUR_UNITField;

    private string qTYField;

    private string bEGDAField;

    private string eNDDAField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string SUBSCRTYP
    {
        get
        {
            return this.sUBSCRTYPField;
        }
        set
        {
            this.sUBSCRTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string DUR
    {
        get
        {
            return this.dURField;
        }
        set
        {
            this.dURField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string DUR_UNIT
    {
        get
        {
            return this.dUR_UNITField;
        }
        set
        {
            this.dUR_UNITField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string QTY
    {
        get
        {
            return this.qTYField;
        }
        set
        {
            this.qTYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string BEGDA
    {
        get
        {
            return this.bEGDAField;
        }
        set
        {
            this.bEGDAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string ENDDA
    {
        get
        {
            return this.eNDDAField;
        }
        set
        {
            this.eNDDAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_SERVICE
{

    private string sIDField;

    private string lTYPEField;

    private string poField;

    private ZSALES_PRODUCT[] pRODField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string SID
    {
        get
        {
            return this.sIDField;
        }
        set
        {
            this.sIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string LTYPE
    {
        get
        {
            return this.lTYPEField;
        }
        set
        {
            this.lTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string PO
    {
        get
        {
            return this.poField;
        }
        set
        {
            this.poField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZSALES_PRODUCT[] PROD
    {
        get
        {
            return this.pRODField;
        }
        set
        {
            this.pRODField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_ECDIS
{

    private string idField;

    private string mODELField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string MODEL
    {
        get
        {
            return this.mODELField;
        }
        set
        {
            this.mODELField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class ZSALES_VESSELS
{

    private string vIDField;

    private string vNAMEField;

    private string iMOField;

    private string cALLSIGNField;

    private string sHOREBASEDField;

    private string fLEETField;

    private string uSERSField;

    private string dISC_CODEField;

    private string eNDUSERIDField;

    private ZSALES_ECDIS[] eCDISField;

    private ZSALES_SERVICE sERField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string VID
    {
        get
        {
            return this.vIDField;
        }
        set
        {
            this.vIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string VNAME
    {
        get
        {
            return this.vNAMEField;
        }
        set
        {
            this.vNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string IMO
    {
        get
        {
            return this.iMOField;
        }
        set
        {
            this.iMOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string CALLSIGN
    {
        get
        {
            return this.cALLSIGNField;
        }
        set
        {
            this.cALLSIGNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string SHOREBASED
    {
        get
        {
            return this.sHOREBASEDField;
        }
        set
        {
            this.sHOREBASEDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string FLEET
    {
        get
        {
            return this.fLEETField;
        }
        set
        {
            this.fLEETField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string USERS
    {
        get
        {
            return this.uSERSField;
        }
        set
        {
            this.uSERSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string DISC_CODE
    {
        get
        {
            return this.dISC_CODEField;
        }
        set
        {
            this.dISC_CODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string ENDUSERID
    {
        get
        {
            return this.eNDUSERIDField;
        }
        set
        {
            this.eNDUSERIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ZSALES_ECDIS[] ECDIS
    {
        get
        {
            return this.eCDISField;
        }
        set
        {
            this.eCDISField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public ZSALES_SERVICE SER
    {
        get
        {
            return this.sERField;
        }
        set
        {
            this.sERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
public partial class Z_SALES_INTERFACEResponse
{

    private string eX_MESSAGEField;

    private string eX_STATUSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string EX_MESSAGE
    {
        get
        {
            return this.eX_MESSAGEField;
        }
        set
        {
            this.eX_MESSAGEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string EX_STATUS
    {
        get
        {
            return this.eX_STATUSField;
        }
        set
        {
            this.eX_STATUSField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class Z_SALES_INTERFACERequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", Order = 0)]
    public Z_SALES_INTERFACE Z_SALES_INTERFACE;

    public Z_SALES_INTERFACERequest()
    {
    }

    public Z_SALES_INTERFACERequest(Z_SALES_INTERFACE Z_SALES_INTERFACE)
    {
        this.Z_SALES_INTERFACE = Z_SALES_INTERFACE;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class Z_SALES_INTERFACEResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", Order = 0)]
    public Z_SALES_INTERFACEResponse Z_SALES_INTERFACEResponse;

    public Z_SALES_INTERFACEResponse1()
    {
    }

    public Z_SALES_INTERFACEResponse1(Z_SALES_INTERFACEResponse Z_SALES_INTERFACEResponse)
    {
        this.Z_SALES_INTERFACEResponse = Z_SALES_INTERFACEResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface z_sales_interfaceChannel : z_sales_interface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class z_sales_interfaceClient : System.ServiceModel.ClientBase<z_sales_interface>, z_sales_interface
{

    public z_sales_interfaceClient()
    {
    }

    public z_sales_interfaceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public z_sales_interfaceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public z_sales_interfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public z_sales_interfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Z_SALES_INTERFACEResponse1 z_sales_interface.Z_SALES_INTERFACE(Z_SALES_INTERFACERequest request)
    {
        return base.Channel.Z_SALES_INTERFACE(request);
    }

    public Z_SALES_INTERFACEResponse Z_SALES_INTERFACE(Z_SALES_INTERFACE Z_SALES_INTERFACE1)
    {
        Z_SALES_INTERFACERequest inValue = new Z_SALES_INTERFACERequest();
        inValue.Z_SALES_INTERFACE = Z_SALES_INTERFACE1;
        Z_SALES_INTERFACEResponse1 retVal = ((z_sales_interface)(this)).Z_SALES_INTERFACE(inValue);
        return retVal.Z_SALES_INTERFACEResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<Z_SALES_INTERFACEResponse1> z_sales_interface.Z_SALES_INTERFACEAsync(Z_SALES_INTERFACERequest request)
    {
        return base.Channel.Z_SALES_INTERFACEAsync(request);
    }

    public System.Threading.Tasks.Task<Z_SALES_INTERFACEResponse1> Z_SALES_INTERFACEAsync(Z_SALES_INTERFACE Z_SALES_INTERFACE)
    {
        Z_SALES_INTERFACERequest inValue = new Z_SALES_INTERFACERequest();
        inValue.Z_SALES_INTERFACE = Z_SALES_INTERFACE;
        return ((z_sales_interface)(this)).Z_SALES_INTERFACEAsync(inValue);
    }
}
